re-open milestone on cherry-pick fail

diff --git a/.github/workflows/cut-rc.yml b/.github/workflows/cut-rc.yml
--- a/.github/workflows/cut-rc.yml
+++ b/.github/workflows/cut-rc.yml
@@ -196,6 +196,24 @@ jobs:
             "${{needs.variables.outputs.branch}}" \
             "${{needs.variables.outputs.named-release-patch}}"
 
+      - name: Re-open "${{needs.variables.outputs.milestone}}" on failed bad-cherries
+        id: reopen-milestone
+        if: failure() && steps.cherry-pick.outputs.bad-cherries != ''
+        env:
+          GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
+        run: |
+          set -uo pipefail
+          if ! RESPONSE=$(gh api -X PATCH \
+            "repos/${{github.repository}}/milestones/${{ github.event.milestone.id }}" \
+            -f state='open' \
+            2>&1); then
+            if grep "HTTP 4" <<< "$RESPONSE"; then
+              echo "::error::Couldn't reopen milestone ${{needs.variables.outputs.milestone}}: $RESPONSE"
+              exit 1
+            fi
+            echo "Re-opened milestone ${{needs.variables.outputs.milestone}} to fix cherry-picks." >> "$GITHUB_STEP_SUMMARY"
+          fi
+
       - name: Post to Slack about picked cherries
         if: failure() && steps.cherry-pick.outputs.bad-cherries != ''
         env:
